### ISSUE TITLE
Add compatibility with the fabric loader 

### ISSUE THREAD

**Issue by thiagogebrimm** [Yunus1903/ChatEmbeds#3]

**Comment by Yunus1903** [comment]
Porting to Fabric shouldn't be that hard but at the moment I don't have time to do it. Either you or someone else can do it and make a pull request, or I can do it when I have some free time again.

I'll leave this issue open for now.

**Comment by braxtonhall** [comment]
I have Fabric support working for 1.18.2. When #6 gets cleaned up I'll PR that as well
