### ISSUE TITLE
hope Support BungeeCord

### ISSUE THREAD

**Issue by coolxitech** [Yunus1903/ChatEmbeds#5]

**Comment by Yunus1903** [comment]
Could you give more details about your request?
This mod was made to work with the Forge modding API.

Bungee Cord is an entirely separate project for a separate purpose. You could of course use both of them to obtain a modded environment. (There might be better alternatives/forks of Bungee Cord for this purpose as well).

**Comment by coolxitech** [comment]
Maybe you can support bungeecord and fabric.

**Comment by coolxitech** [comment]
game in send anything image!

**Comment by Yunus1903** [comment]
This still doesn't answer my question. I will close this issue for now.
If you can provide more details about your issue then we might be able to work something out.

As for fabric support, this has been on my mind. Not any time soon though. You can follow #3 for more on that.
